name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  singer-vite-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7

      - name: Install Node.js
        uses: actions/setup-node@v6
        with: 
          node-version: 22
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run linting check
        run: npm run lint

      